---
builds:
  - id: tube
    binary: tube
    main: .
    flags:
      - -installsuffix=netgo
    tags:
      - embed
      - netcgo
      - static_build
    ldflags: >-
      -w
      -X git.mills.io/prologic/tube.Version={{.Version}}
      -X git.mills.io/prologic/tube.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - freebsd
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates: ["prologic/tube:{{ .Version }}-amd64"]
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - ".dockerfiles/entrypoint.sh"
      - ".dockerfiles/config.json"
  - image_templates: ["prologic/tube:{{ .Version }}-arm64v8"]
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    extra_files:
      - ".dockerfiles/entrypoint.sh"
      - ".dockerfiles/config.json"

docker_manifests:
  - name_template: prologic/tube:{{ .Version }}
    image_templates:
      - prologic/tube:{{ .Version }}-amd64
      - prologic/tube:{{ .Version }}-arm64v8

signs:
  - artifacts: checksum
release:
  gitea:
    owner: prologic
    name: tube
  draft: false
gitea_urls:
  api: https://git.mills.io/api/v1/
